dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('error404/', views.error404, name='E404'), 
    path('error404/', views.error403, name='E403'), 
    path('buscar/', views.buscar, name='buscar'),   
    path('change_language/<str:lang_code>/', views.change_language, name='change_language'),
    path('estudiantesDashboard/', views.estudiante_dashboard ,name='estudiante_dashboard')
]

seda_inscripciones/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('chocopegajoso_chocopato/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'), name='Home'),
    path('', views.login_view, name='login'),
    path('registro/', views.registrar_estudiante, name='registrar_estudiante'),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('usuarios/', include('usuarios.urls'), name='usuarios'),
    path('estudiantes/', include('estudiantes.urls'), name='estudiantes'),
    path('auditoria/', include('auditoria.urls'), name='auditoria'),
    path('select2/', include('django_select2.urls')),
    path('cerrar_sesion/', views.cerrar_sesion, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #Empleados
    path('', views.usuarios, name='usuarios'),
    path('empleados/', views.mostrarUsuarios, name='empleados'),
    path('addUsers/', views.addUsuarios, name='addUsers'),
    path('actUsers/<id>/', views.actUsuarios, name='actUsers'),
    path('dltUsers/<id>/', views.dltUsuarios, name='dltUsers'),
    path('verEmpleado/<id>/', views.tarjetaUsuarios, name='viewUser'),
    path('user/<int:user_id>/asignar_permiso/<int:permission_id>/', views.asignar_permiso, name='asignar_permiso'),
    path('user/quitar_permiso/<int:user_id>/', views.quitar_permiso, name='quitar_permiso'),
    path('user/<int:user_id>/permissions/', views.view_user_permissions, name='view_user_permissions'),
    path('cuentaBloqueada/', views.cuenta_bloqueada, name='cuenta_bloqueada'),
    path('actualizar_perfil/', views.actualizar_perfil_empleado, name='actualizar_perfil_empleado'),
    
    #Cargos
    path('cargos/', views.Cargos, name='cargos'),
    path('actCargos/<id>/', views.actCargos, name='actCargos'),
    path('dltCargos/<id>/', views.dltCargos, name='dltCargos'),
]

dashboard/models.py
from django.db import models

# Create your models here.

usuarios/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from PIL import Image
import re
from auditlog.registry import auditlog
from datetime import date
from django.utils.timezone import now

# Modelo para los cargos
class Cargo(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

# Opciones para género
class GeneroChoices(models.TextChoices):
    MASCULINO = 'M', _('Masculino')
    FEMENINO = 'F', _('Femenino')

# Validaciones
# ... (Mantenemos las mismas funciones de validación)

def validar_nombre(value):
    regex = r"^[a-zA-ZñÑáéíóúÁÉÍÓÚ ]+$"
    pattern = re.compile(regex)
    if not pattern.match(value):
        raise ValidationError("El nombre no tiene el formato correcto. Asegúrate de usar solo letras y espacios.")

def validar_fecha_nacimiento(value):
    if value > date.today():
        raise ValidationError("La fecha de nacimiento no puede ser futura.")

def validar_foto_perfil(value):
    try:
        img = Image.open(value)
        if img.format not in ['JPEG', 'PNG']:
            raise ValidationError("La imagen debe ser en formato JPEG o PNG.")
    except IOError:
        raise ValidationError("El archivo no es una imagen válida.")

def validar_pasaporte(value):
    """
    Valida que el pasaporte tenga un formato alfanumérico válido.
    Ejemplo: Debe contener entre 6 y 9 caracteres alfanuméricos.
    """
    regex = r"^[a-zA-Z0-9]{6,9}$"
    pattern = re.compile(regex)
    if not pattern.match(value):
        raise ValidationError("El pasaporte debe contener entre 6 y 9 caracteres alfanuméricos.")
    
# Modelo base abstracto
class CustomUser(AbstractUser):
    nombre = models.CharField(max_length=50, validators=[validar_nombre], blank=True)
    apellido = models.CharField(max_length=50, validators=[validar_nombre], blank=True)
    pasaporte = models.CharField(
        max_length=9,
        unique=True,
        verbose_name=_('Pasaporte'),
        validators=[validar_pasaporte],
        blank=True
    )
    telefono = models.CharField(
        max_length=15,
        blank=True,
        null=True,
        verbose_name=_('Teléfono'),
    )
    genero = models.CharField(
            max_length=1,
            choices=GeneroChoices.choices,
            default=GeneroChoices.MASCULINO,
            verbose_name=_('Género'),
            blank=True
        )
    direccion = models.TextField(blank=True, null=True, verbose_name=_('Dirección'))
    fecha_nacimiento = models.DateField(
        verbose_name=_('Fecha de nacimiento'),
        validators=[validar_fecha_nacimiento],
        null=True,
        blank=True
    )
    foto_perfil = models.ImageField(
        upload_to='usuarios/',
        default='perfil/default.jpg',
        validators=[validar_foto_perfil],
        blank=True
    )

    status = models.BooleanField(default=True, verbose_name=_('Estado de Cuenta'))

    fecha_creacion = models.DateTimeField(auto_now_add=True)

    @property
    def edad(self):
        if self.fecha_nacimiento:
            hoy = date.today()
            edad = hoy.year - self.fecha_nacimiento.year
            if (hoy.month, hoy.day) < (self.fecha_nacimiento.month, self.fecha_nacimiento.day):
                edad -= 1
            return edad
        return None

    @property
    def dias_para_cumple(self):
        if self.fecha_nacimiento:
            hoy = date.today()
            proximo_cumple = self.fecha_nacimiento.replace(year=hoy.year)
            if proximo_cumple < hoy:
                proximo_cumple = proximo_cumple.replace(year=hoy.year + 1)
            return (proximo_cumple - hoy).days
        return None

    @property
    def tiempo_desde_registro(self):
        if self.fecha_creacion:
            return (now() - self.fecha_creacion).days
        return None

    def save(self, *args, **kwargs):
        if not self.username:  # Si no se proporciona un username
            self.username = f"{self.email.split('@')[0]}_{self.pasaporte}"  # Generar un username único basado en el email y pasaporte
        super().save(*args, **kwargs)

# Modelo de Empleado
class Empleado(CustomUser):
    cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE, verbose_name=_('Cargo'), null=True, blank=True)

    def __str__(self):
        return f"Empleado: {self.nombre} {self.apellido} ({self.pasaporte})"
    
auditlog.register(Empleado)

dashboard/views.py
from django.shortcuts import render, redirect
from usuarios.models import Empleado
from estudiantes.models import Estudiantes, DocumentosEstudiante
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from estudiantes.models import DocumentosEstudiante
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.utils.translation import activate
from django.conf import settings
from django.utils.translation import get_language
from django.utils.translation import gettext_lazy as _
# Create your views here.

def change_language(request, lang_code):
    if lang_code in dict(settings.LANGUAGES):
        activate(lang_code)
        request.session['django_language'] = lang_code  # Guarda el idioma en la sesión
        print(f"Idioma cambiado a: {lang_code}")  # Depuración
    else:
        print(f"Idioma no válido: {lang_code}")  # Depuración
    return redirect(request.META.get('HTTP_REFERER', '/'))

@login_required
def dashboard(request):
    # Forzar el idioma desde la sesión
    lang_code = request.session.get('django_language', 'en')  # Idioma por defecto: 'es'
    activate(lang_code)

    # Contar usuarios y estudiantes
    Megumi = Empleado.objects.count()
    Itadori = Estudiantes.objects.count()

    # Contar documentos pendientes, aprobados y rechazados
    documentos_pendientes = DocumentosEstudiante.objects.filter(estado_inscripcion="En Revisión").count()
    documentos_aprobados = DocumentosEstudiante.objects.filter(estado_inscripcion="Aprobado").count()
    documentos_rechazados = DocumentosEstudiante.objects.filter(estado_inscripcion="Rechazado").count()

    # Obtener los documentos pendientes para mostrarlos en el dashboard
    documentos_pendientes_lista = DocumentosEstudiante.objects.filter(estado_inscripcion="En Revisión").order_by('-fecha_subida')[:5]  # Mostrar los 5 más recientes

    # Paginación de estudiantes
    Maki = Estudiantes.objects.all().order_by('-id')  # Ordenar por el campo 'id'
    page = request.GET.get('page', 1)
    paginator = Paginator(Maki, 5)

    try:
        Maki = paginator.page(page)
    except (EmptyPage, PageNotAnInteger):
        Maki = paginator.page(paginator.num_pages)

    # Contexto para la plantilla
    context = {
        'page_title': 'SEDA | Dashboard',
        'usuarios': Megumi,  # Total de empleados
        'estudiantes': Itadori,  # Total de estudiantes
        'Zenin': Maki,  # Lista de estudiantes paginada
        'paginator': paginator,  # Paginador
        'pendientes': documentos_pendientes,  # Total de documentos pendientes
        'aprobados': documentos_aprobados,  # Total de documentos aprobados
        'rechazados': documentos_rechazados,  # Total de documentos rechazados
        'documentos_pendientes_lista': documentos_pendientes_lista,  # Lista de documentos pendientes
    }

    return render(request, "dashboard.html", context)

@login_required
def buscar(request):
    
    lang_code = request.session.get('django_language', 'en')  # Idioma por defecto: 'es'
    activate(lang_code)
    
    query = request.GET.get('q', '').strip()
    if not query:
        messages.error(request, _('Please enter a valid search term.'))
        return redirect('dashboard')

    # Buscar en Empleados
    try:
        user = Empleado.objects.get(username=query)
        return redirect('viewUser', id=user.id)  # Cambiar 'user_id' por 'id'
    except Empleado.DoesNotExist:
        pass

    try:
        user = Empleado.objects.get(nombre__icontains=query)
        return redirect('viewUser', id=user.id)  # Cambiar 'user_id' por 'id'
    except Empleado.DoesNotExist:
        pass

    try:
        user = Empleado.objects.get(pasaporte=query)
        return redirect('viewUser', id=user.id)  # Cambiar 'user_id' por 'id'
    except Empleado.DoesNotExist:
        pass
    
    try:
        user = Empleado.objects.get(email__icontains=query)
        return redirect('viewUser', id=user.id)  # Cambiar 'user_id' por 'id'
    except Empleado.DoesNotExist:
        pass

    # Buscar en Estudiantes
    try:
        estudiante = Estudiantes.objects.get(nombre__icontains=query)
        return redirect('verEstudiante', id=estudiante.id)
    except Estudiantes.DoesNotExist:
        pass

    try:
        estudiante = Estudiantes.objects.get(pasaporte__icontains=query)
        return redirect('verEstudiante', id=estudiante.id)
    except Estudiantes.DoesNotExist:
        pass
    
    try:
        estudiante = Estudiantes.objects.get(pasaporte__icontains=query)
        return redirect('verEstudiante', id=estudiante.id)
    except Estudiantes.DoesNotExist:
        pass

    # Buscar en Documentos
    documento = DocumentosEstudiante.objects.filter(codigo_inscripcion__icontains=query)
    if documento.exists():
        return redirect('visualizarDocumento', id=documento.first().id)

    return redirect('E404')

@login_required
def error404(request): 
    
    lang_code = request.session.get('django_language', 'en')  # Idioma por defecto: 'es'
    activate(lang_code)
    
    context = {
        'page_title': 'SEDA | No se encontro la informacion'
    }
    
    return render(request, "error-404.html", context)

def error403(request): 
    
    context = {
        'page_title': 'SEDA | No tienes permisos para estar aqui'
    }
    
    return render(request, "error-403.html", context)

@login_required
def estudiante_dashboard(request):
    
    lang_code = request.session.get('django_language', 'en')  # Idioma por defecto: 'es'
    activate(lang_code)
    
    # Obtener los documentos del estudiante logueado
    documentos = DocumentosEstudiante.objects.filter(estudiante=request.user).first()

    # Calcular el progreso de los documentos subidos
    progreso = documentos.calcular_progreso() if documentos else 0

    # Paginación de los documentos (si es necesario)
    Maki = [documentos] if documentos else []  # Convertir a lista para paginar
    page = request.GET.get('page', 1)
    paginator = Paginator(Maki, 5)

    try:
        Maki = paginator.page(page)
    except (EmptyPage, PageNotAnInteger):
        Maki = paginator.page(paginator.num_pages)

    context = {
        'page_title': 'SEDA | Dashboard - Estudiantes',
        'Zenin': Maki,  # Paginador de documentos
        'progreso': progreso,  # Progreso de los documentos subidos
        'paginator': paginator,
        'documentos': documentos,  # Pasamos los documentos al contexto
    }

    return render(request, "dashboardEstudiantes.html", context)

dashboard/templates/dashboard.html
{% extends 'Base/head.html' %}
{% load i18n %}
{% block Osvell %}
  <div class="main-content">
    <section class="section">
      {% if messages %}
      <div class="alert alert-success">
        {% for message in messages %}
        <p>{{ message }}</p>
        {% endfor %}
      </div>
      {% endif %}
      <div class="row">
        <!-- Student Card -->
        {% if perms.estudiantes.view_estudiantes %}
        <div class="col-lg-6 col-md-4 col-sm-12">
          <div class="card card-statistic-2">
            <a href="{% url 'estudiantes' %}" style="text-decoration: none; color: black;">
              <div class="card-stats">
                <div class="card-stats-title">{% trans "Students" %}</div>
                <div class="card-stats-items">
                  <div class="card-stats-item">
                    <div class="card-stats-item-count">{{ rechazados }}</div>
                    <div class="card-stats-item-label">{% trans "Rejected" %}</div>
                  </div>
                  <div class="card-stats-item">
                    <div class="card-stats-item-count">{{ pendientes }}</div>
                    <div class="card-stats-item-label">{% trans "Pending" %}</div>
                  </div>
                  <div class="card-stats-item">
                    <div class="card-stats-item-count">{{ aprobados }}</div>
                    <div class="card-stats-item-label">{% trans "Approved" %}</div>
                  </div>
                </div>
              </div>
              <div class="card-icon shadow-primary bg-primary">
                <i class="fas fa-users"></i>
              </div>
              <div class="card-wrap">
                <div class="card-header">
                  <h4>{% trans "Students" %}</h4>
                </div>
                <div class="card-body">
                  {{ estudiantes }}
                </div>
              </div>
            </a>
          </div>
        </div>
        {% endif %}

        <!-- User Card -->
        {% if perms.usuarios.view_customuser %}
        <div class="col-lg-6 col-md-4 col-sm-12">
          <div class="card card-statistic-2">
            <a href="{% url 'usuarios' %}" style="text-decoration: none; color: black;">
              <div class="card-chart">
                <canvas id="balance-chart" height="80"></canvas>
              </div>
              <div class="card-icon shadow-primary bg-primary">
                <i class="fas fa-user-tie"></i>
              </div>
              <div class="card-wrap">
                <div class="card-header">
                  <h4>{% trans "System Users" %}</h4>
                </div>
                <div class="card-body">
                  {{ usuarios }}
                </div>
              </div>
            </a>
          </div>
        </div>
        {% endif %}
      </div>

      <!-- Last Registered Students Table -->
      {% if perms.estudiantes.view_estudiantes %}
      <div class="row">
        <div class="col-md-8">
          <div class="card">
            <div class="card-header">
              <h4>{% trans "Latest Registered Students" %}</h4>
              <div class="card-header-action">
                <a href="{% url 'lista_estudiantes' %}" class="btn btn-outline-danger">{% trans "See More" %} <i class="fas fa-chevron-right"></i></a>
              </div>
            </div>
            <div class="card-body p-0">
              <div class="table-responsive table-invoice">
                <table class="table table-striped mb-0">
                  <thead>
                    <tr>
                      <th>{% trans "Students" %}</th>
                      <th>{% trans "Addition Date" %}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% if Zenin %}
                    {% for c in Zenin %}
                    <tr>
                      <td>
                        <a href="{% url 'verEstudiante' c.id %}" class="font-weight-600">
                          <img src="{{ c.foto_perfil.url }}" alt="{{ c.nombre }}" width="30" class="rounded-circle mr-1">
                          {{ c.nombre }} {{ c.apellido }}
                        </a>
                      </td>
                      <td>
                        {{ c.fecha_creacion }}
                      </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                      <td colspan="3" style="text-align: center;">{% trans "No records" %}</td>
                    </tr>
                    {% endif %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

        <!-- Pending Processes Card -->
        <div class="col-md-4">
          <div class="card card-hero">
            <div class="card-header">
              <div class="card-icon">
                <i class="far fa-question-circle"></i>
              </div>
              <h4>{{ pendientes }}</h4>
              <div class="card-description">{% trans "Processes to Approve" %}</div>
            </div>
            <div class="card-body p-0">
              <div class="tickets-list">
                {% for d in documentos_pendientes_lista %}
                <a href="{% url 'visualizarDocumento' d.id %}" class="ticket-item">
                  <div class="ticket-title">
                    <h4>{{ d.estudiante.nombre }} {{ d.estudiante.apellido }}</h4>
                  </div>
                  <div class="ticket-info">
                    <div>{{ d.codigo_inscripcion }}</div>
                    <div class="bullet"></div>
                    <div class="text-primary">
                      {% with d.fecha_subida|timesince as tiempo %}
                        {{ tiempo }} {% trans 'waiting' %}
                      {% endwith %}
                    </div>
                  </div>
                </a>
                {% empty %}
                <div class="ticket-item">
                  <div class="ticket-title">
                    <h4>{% trans "No pending processes" %}</h4>
                  </div>
                </div>
                {% endfor %}
                <a href="{% url 'documentos_pendientes' %}" class="ticket-item ticket-more">
                  {% trans 'See all' %} <i class="fas fa-chevron-right"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
    </section>
  </div>
{% endblock %}

dashboard/templates/dashboardEstudiantes.html
{% extends 'Base/head2.html' %}
{% load static %}
{% load i18n %}
{% block Osvell %}
<div class="main-content">
  <section class="section">
    {% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
        <p>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}
    <div class="section-header d-flex justify-content-between align-items-center">
      {% if user.is_authenticated %}
        <h1 class="mb-0">{% trans "Greetings" %}: {{user.nombre}} {{user.apellido}}</h1>
      {% endif %}
      <div class="d-flex align-items-center">
        <a href="https://www.sedaexperience.com/pagos/" target="_blank">
        <img src="{% static 'img/button_pay.jpg' %}" width="120" alt="">
        </a>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-md-6 col-sm-6 col-12">
        {% if documentos %}
        <a href="{% url 'actualizar_documentos' documentos.id %}" style="text-decoration: none;">
          <div class="card card-statistic-1">
              <div class="card-icon bg-warning">
                  <i class="fas fa-edit"></i>
              </div>
              <div class="card-wrap">
                  <div class="card-header">
                      <h4>{% trans "Update Documents" %}</h4>
                  </div>
                  <div class="card-body">
                    {% trans "Click here" %}
                  </div>
              </div>
          </div>
      </a>
        {% else %}
            <a href="{% url 'subir_documentos' %}" style="text-decoration: none;">
                <div class="card card-statistic-1">
                    <div class="card-icon bg-primary">
                        <i class="fas fa-upload"></i>
                    </div>
                    <div class="card-wrap">
                        <div class="card-header">
                            <h4>{% trans "Upload Documents" %}</h4>
                        </div>
                        <div class="card-body">
                          {% trans "Click here" %}
                        </div>
                    </div>
                </div>
            </a>
        {% endif %}
    </div>
    
      <div class="col-lg-4 col-md-6 col-sm-6 col-12">
        <div class="card card-statistic-1 shadow" style="border-radius: 10px; overflow: hidden; background-color: {% if progreso == 100 %}#28a745{% elif progreso >= 50 %}#ffc107{% else %}#dc3545{% endif %};">
          <div class="card-icon d-flex align-items-center justify-content-center" style="width: 80px; height: 80px; background-color: rgba(255, 255, 255, 0.2); border-radius: 50%; margin: 15px auto;">
            <i class="fas fa-tasks text-white" style="font-size: 30px;"></i>
          </div>
          <div class="card-wrap text-center">
            <div class="card-header">
              <h4 class="text-white" style="font-weight: bold;">{% trans "Enrollment Progress" %}</h4>
            </div>
            <div class="card-body">
              <span class="text-white" style="font-size: 24px; font-weight: bold;">{{ progreso }}%</span>
              <p class="text-white" style="margin: 0; font-size: 14px;">{% trans "Completed" %}</p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-6 col-12">
        {% if user.status == True %}
          <div class="card card-statistic-1">
          <div class="card-icon bg-success">
            <i class="fas fa-circle"></i>
          </div>
          <div class="card-wrap">
            <div class="card-header">
              <h4>{% trans "Account Status" %}</h4>
            </div>
            <div class="card-body">
              {% trans "Active" %}
            </div>
          </div>
          </div>
        {% else %}
          <div class="card card-statistic-1">
          <div class="card-icon bg-danger">
            <i class="fas fa-circle"></i>
          </div>
          <div class="card-wrap">
            <div class="card-header">
              <h4>{% trans "Account Status" %}</h4>
            </div>
            <div class="card-body">
              {% trans "Inactive" %}
            </div>
          </div>
          </div>
        {% endif %}
      </div>                  
    </div>
  </section>
  <div class="row">
    <div class="col-12 col-md-12 col-lg-12">
      <div class="card">
        <div class="card-header">
          <h4>{% trans "Documents" %}</h4>
        </div>
        <div class="card-body p-0">
          <div class="table-responsive">
            <table class="table table-striped">
              <tbody>
                <tr>
                  <th>{% trans "Name" %}</th>
                  <th>{% trans "Date" %}</th>
                  <th>{% trans "Status" %}</th>
                  <th>{% trans "Reference Code" %}</th>
                </tr>
                {% for documento in Zenin %}
                  <tr>
                    <td>{{ documento.estudiante.nombre }} {{ documento.estudiante.apellido }}</td>
                    <td>{{ documento.fecha_subida }}</td>
                    <td>
                      {% if documento.estado_inscripcion == "En Revisión" %}
                          <span class="badge badge-warning">{% trans "Under Review" %}</span>
                      {% elif documento.estado_inscripcion == "Aprobado" %}
                          <span class="badge badge-success">{% trans "Approved" %}</span>
                      {% else %}
                          <span class="badge badge-danger">{% trans "Rejected" %}</span>
                      {% endif %}
                  </td>                  
                    <td>{{documento.codigo_inscripcion}}</td>
                  </tr>
                  <tr>
                    {% if documento.mensaje_rechazo %}
                      <th>{% trans "Cancellation Message" %}</th>
                      <td colspan="4" class="alert alert-danger">{{documento.mensaje_rechazo}}</td>
                    {% endif %}
                  </tr>
                {% empty %}
                  <tr>
                    <td colspan="4">{% trans "No documents uploaded" %}.</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

dashboard/templates/error-403.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>{{page_title}}</title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="{% static 'modules/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'modules/fontawesome/css/all.min.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- CSS Libraries -->
  <link rel="stylesheet" href="{% static 'modules/jqvmap/dist/jqvmap.min.css' %}">
  <link rel="stylesheet" href="{% static 'modules/summernote/summernote-bs4.css' %}">
  <link rel="stylesheet" href="{% static 'modules/owlcarousel2/dist/assets/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'modules/owlcarousel2/dist/assets/owl.theme.default.min.css' %}">
  

  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/components.css' %}">
<!-- Start GA -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-94034622-3');
</script>
<!-- /END GA --></head>

<body>
    <div id="app">
        <section class="section">
          <div class="container mt-5">
            <div class="page-error">
              <div class="page-inner">
                <h1>403</h1>
                <div class="page-description">
                    You do not have access to this page.
                </div>
                <div class="page-search">
                  <form>              	
                    <div class="form-group floating-addon floating-addon-not-append">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">                          
                            <i class="fas fa-search"></i>
                          </div>
                        </div>
                        <input type="text" class="form-control" placeholder="Search">
                        <div class="input-group-append">
                          <button class="btn btn-primary btn-lg">
                            Search
                          </button>
                        </div>
                      </div>
                    </div>
                  </form>
                  <div class="mt-3">
                    <a href="index.html">Back to Home</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="simple-footer mt-5">
              Copyright &copy; Stisla 2018
            </div>
          </div>
        </section>
      </div>
  
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      document.getElementById("year").textContent = new Date().getFullYear();
    });
  </script>
  
</div>
</div>

  <script src="{% static 'modules/jquery.min.js' %}"></script>
  <script src="{% static 'modules/popper.js' %}"></script>
  <script src="{% static 'modules/tooltip.js' %}"></script>
  <script src="{% static 'modules/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'modules/nicescroll/jquery.nicescroll.min.js' %}"></script>
  <script src="{% static 'modules/moment.min.js' %}"></script>
  <script src="{% static 'js/stisla.js' %}"></script>
  <script src="{% static 'js/Eliminar.js' %}"></script>
  
  <!-- JS Libraies -->
  <script src="{% static 'modules/jquery.sparkline.min.js' %}"></script>
  <script src="{% static 'modules/chart.min.js' %}"></script>
  <script src="{% static 'modules/owlcarousel2/dist/owl.carousel.min.js' %}"></script>
  <script src="{% static 'modules/summernote/summernote-bs4.js' %}"></script>
  <script src="{% static 'modules/chocolat/dist/js/jquery.chocolat.min.js' %}"></script>

  <!-- Page Specific JS File -->
  <script src="{% static 'js/page/index.js' %}"></script>
  
  <!-- Template JS File -->
  <script src="{% static 'js/scripts.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>

  <!-- jQuery -->
<script src="{% static 'modules/jquery.min.js' %}"></script>
</body>
</html>